### ISSUE TITLE
Failed to load resource: net::ERR_CERT_DATE_INVALID

### ISSUE THREAD

**Issue by ttpro1995** [paperscape/paperscape-mapclient#9]
Cannot do anything. 
When I open Chrome dev console, it said

> Failed to load resource: net::ERR_CERT_DATE_INVALID

**Comment by ttpro1995** [comment]
look like you lost your SSL

**Comment by dpgeorge** [comment]
Thanks for the report.

@rknegjens what was the status with HTTPS?

**Comment by rknegjens** [comment]
@dpgeorge conversion was done and working. Are the letsencrypt certs set to auto renew e.g. via cron?

**Comment by dpgeorge** [comment]
> Are the letsencrypt certs set to auto renew e.g. via cron?

Yes.  Running `certbot renew` says that everything is up to date, no action needed.

**Comment by rknegjens** [comment]
The issue seems to be the expiry of the certificate after 3 months:

![image](https://user-images.githubusercontent.com/1302152/57007669-c3064c80-6bea-11e9-91ad-a55e86131e33.png)

Could you try a certbot --force-renew and/or restarting/reloading the webserver?

**Comment by dpgeorge** [comment]
Reloading nginx config seems to have fixed it, it's now using the new certificate (which was issued March 27th).
